branch-defaults:
  main:
    environment: null
    group_suffix: null
global:
  application_name: yt-tab-img-extractor-main
  branch: null
  default_platform: Python 3.13 running on 64bit Amazon Linux 2023
  default_region: ap-northeast-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  workspace_type: Application
